version: '3.8'

services:
  vite-dev:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - vite-node-modules:/app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

volumes:
  vite-node-modules:
